    name: Deploy to Staging
    on:
        push:
            branches:
                - "main"
  
jobs:
    redeploy_everything:
        name: Deploy to Staging

        steps:
            - name: SSH  into staging server
            - run: |
                echo ${{secrets.SSH_PRIVATE_KEY}} &> ~/shh_key
                ssh -i ~/shh_key root@128.199.29.186
                cd ci-next-app && git pull
                pnpm install
                pnpm run build
                pm2 restart fe-server
                pm2 restart http-server
                pm2 restart ws-server


              
